// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dump
Rcpp::DataFrame dump(std::string filename);
RcppExport SEXP synder_dump(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(dump(filename));
    return rcpp_result_gen;
END_RCPP
}
// search
Rcpp::DataFrame search(std::string synfilename, std::string intfilename);
RcppExport SEXP synder_search(SEXP synfilenameSEXP, SEXP intfilenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type synfilename(synfilenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type intfilename(intfilenameSEXP);
    rcpp_result_gen = Rcpp::wrap(search(synfilename, intfilename));
    return rcpp_result_gen;
END_RCPP
}
// filter
Rcpp::DataFrame filter(std::string synfilename, std::string intfilename);
RcppExport SEXP synder_filter(SEXP synfilenameSEXP, SEXP intfilenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type synfilename(synfilenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type intfilename(intfilenameSEXP);
    rcpp_result_gen = Rcpp::wrap(filter(synfilename, intfilename));
    return rcpp_result_gen;
END_RCPP
}
// map
Rcpp::DataFrame map(std::string synfilename, std::string intfilename);
RcppExport SEXP synder_map(SEXP synfilenameSEXP, SEXP intfilenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type synfilename(synfilenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type intfilename(intfilenameSEXP);
    rcpp_result_gen = Rcpp::wrap(map(synfilename, intfilename));
    return rcpp_result_gen;
END_RCPP
}
// count
Rcpp::DataFrame count(std::string synfilename, std::string intfilename);
RcppExport SEXP synder_count(SEXP synfilenameSEXP, SEXP intfilenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type synfilename(synfilenameSEXP);
    Rcpp::traits::input_parameter< std::string >::type intfilename(intfilenameSEXP);
    rcpp_result_gen = Rcpp::wrap(count(synfilename, intfilename));
    return rcpp_result_gen;
END_RCPP
}
