# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' print all blocks with contiguous set ids
#'
#' @param filename synteny map file name
#' @export
dump <- function(filename) {
    .Call('synder_dump', PACKAGE = 'synder', filename)
}

#' predict search intervals
#'
#' @param synfilename synteny map file name
#' @param gfffilename GFF file name
#' @export
search <- function(synfilename, intfilename) {
    .Call('synder_search', PACKAGE = 'synder', synfilename, intfilename)
}

#' remove links that disagree with the synteny map
#'
#' @param synfilename synteny map file name
#' @param intfilename int file name
#' @export
filter <- function(synfilename, intfilename) {
    .Call('synder_filter', PACKAGE = 'synder', synfilename, intfilename)
}

#' trace intervals across genomes
#'
#' @param synfilename synteny map file name
#' @param intfilename int file name
#' @export
map <- function(synfilename, intfilename) {
    .Call('synder_map', PACKAGE = 'synder', synfilename, intfilename)
}

#' count overlaps
#'
#' @param synfilename synteny map file name
#' @param intfilename int file name
#' @export
count <- function(synfilename, intfilename) {
    .Call('synder_count', PACKAGE = 'synder', synfilename, intfilename)
}

